### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by jhigginbotham64** [jhigginbotham64/Starlight.jl#12]
Relying on the debug macro is very limiting. Starlight needs a better logging system, preferably one that supports logging to file/network/etc.

**Comment by Clemapfel** [comment]
If the PR gets merged, this issue may not necessarily be closed. The PR only provides the logging environment, and replaces old `@debug` with new `Log.@debug`. The logging environment is properly set up with `awake!(App)` and properly quit with `shutdown!(App)`. 

However, many things like 
+ start / shutdown of the app
+ successful initialization of the Telescope backend
+ any load of a texture 
+ controllers / keyboards connecting / disconnecting 
+ windows being resized 
+ etc.

Should trigger a `Log.@log`. This is not part of the PR.
