### ISSUE TITLE
Add logo to README

### ISSUE THREAD

**Issue by jhigginbotham64** [jhigginbotham64/Starlight.jl#19]
You know, the one used on the documentation website? The one in docs/src/assets? That I could probably add to the README myself, if I could be bothered to figure out how to
1. link images in GitHub Markdown
2. center it properly
...that one?

I want someone else to take care of it.

**Comment by dhanukaperera** [comment]
I created a PR for this issue : https://github.com/jhigginbotham64/Starlight.jl/pull/23

**Comment by jhigginbotham64** [comment]
Thanks @dhanukaperera, let's [get in touch](https://github.com/jhigginbotham64/Starlight.jl#contact) to discuss payment.
