### ISSUE TITLE
Improve flexibility of ECS

### ISSUE THREAD

**Issue by silversquirl** [jhigginbotham64/Starlight.jl#24]
It would be nice to allow users of Starlight to create their own components in the ECS, so they can make use of component iteration in their own systems.

This would need some way of modifying `Starlight.components` prior to the creation of the ECS - perhaps a config parameter passed into the `App` constructor? Or maybe allow directly modifying `components` and just document that the modifications must occur before the app is created?

I'm not hugely familiar with Julia yet, so there may be a much more elegant solution I'm missing!

**Comment by jhigginbotham64** [comment]
I'm not sure modifying `Starlight.components` would be the best approach. Ideally the whole thing would be reactive.

What we need is an API for building the ECS, maybe even using an actual [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) and/or its [fluent form](https://medium.com/@jacobcunningham/the-fluent-builder-pattern-ac1b6c23afc3).

This API might also serve as the foundation of a way to validate the properties that entities need to be present, i.e. you can't use most `Renderable`s without `pos`.

It might help to come up with a compelling use case. Maybe take a look at Julia's other ECS packages to see how they do things and/or what they're used for? Maybe even check out Unity's ECS documentation?

**Comment by jhigginbotham64** [comment]
My work on the actors branch has resolved this, still ironing out the kinks but most of the hard work is done.
